---
kind: pipeline
type: kubernetes
name: default

steps:
- name: build_docs
  image: sphinxdoc/sphinx
  commands:
  - cd docs
  - make html
- name: build_and_publish
  image: plugins/docker
  settings:
    repo: registry.kill9.bacon/arcanum/gafkalodocs
    registry: registry.kill9.bacon
    username:
      from_secret: dockeruser
    password:
      from_secret: dockerpassword
    debug: true
    tags: "${DRONE_COMMIT:0:7}"
    insecure: true
    dockerfile: Dockerfile.docs
- name: deploy_with_helm
  image: pelotech/drone-helm3
  skip_tls_verify: true
  helm_command: upgrade
  chart: ./docs/helm
  release: gafkalodocs
  values_files:
    from_secret: helm_values
  values: "image.tag=${DRONE_COMMIT:0:7}"
  environment:
    KUBE_API_SERVER:
      from_secret: api_server
    KUBE_CERTIFICATE:
      from_secret: k8s_cert
    KUBE_TOKEN:
      from_secret: k8s_token


