---
kind: pipeline
type: kubernetes
name: default

steps:
- name: build_docs
  image: sphinxdoc/sphinx
  commands:
  - cd docs
  - make html
- name: build_and_publish
  image: plugins/docker
  settings:
    repo: registry.kill9.bacon/arcanum/gafkalodocs
    registry: registry.kill9.bacon
    username:
      from_secret: dockeruser
    password:
      from_secret: dockerpassword
    debug: true
    tags: "${DRONE_COMMIT:0:7}"
    insecure: true
    dockerfile: Dockerfile.docs
