---
kind: pipeline
type: kubernetes
name: default

steps:
- name: backend
  image: sphinxdoc/sphinx
  commands:
  - cd docs
  - make html
- name: build_and_publish
  image: plugins/docker
  settings:
    repo: registry.kill9.bacon/arcanum/gafkalodocs
    username:
      from_secret: dockeruser
    password:
      from_secret: dockerpassword
